---
title: "Homework 5 Answers"
author: "Xuan Beatty"
date: "2025-12-01"
output: pdf_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(
  echo = TRUE,
  results = 'markup',
  warning = FALSE,
  message = FALSE,
  error = FALSE)

```

## Libraries needed

```{r}

library(dplyr)
library(tidyr)
library(broom)
library(purrr)
library(ggplot2)
library(stringr)
library(lubridate)
library(here)

```

## Reading in the data

```{r reading in the data}

homicides <- read.csv(here("data", "homicide-data.csv"))

# Creating a new column combining city and state
homicides <- homicides %>%
  mutate(city_name = paste(city, state, sep = ", "))

homicides <- homicides %>%
  mutate(reported_date = ymd(reported_date))

```

## Selecting only Baltimore Data

```{r selecting baltimoredata}

baltimore_monthly <- homicides %>%
  filter(city_name == "Baltimore, MD") %>%
  mutate(month = floor_date(reported_date, "month")) %>%
  count(month, name = "homicides")

baltimore_monthly <- baltimore_monthly %>%
  mutate(
    season = ifelse(month(month) %in% c(11,12,1,2,3,4),
                    "Winter", "Summer")
  )

freddie_date <- as.Date("2015-04-12")


```

